data class Employee(
    val FirstName: String = "",
    val LastName: String = "",
    val EmployeeCode: String = "",
    val Email: String = "",
    val PhoneNumber: String = "",

    val Photo: String = "",
    val ShopId: String = "",
    val TotalTips: String = "",
    val TipType: String = "",
    val JobTitle: String = "",
    val Status: String = "",
    val ShowAbbreviatedName: String = "",
    val Ratings: String = "",
    val Locations: String = "",
    val ID: String = "",
    val Description: String = "",
    val Rating: String = "",
    val PaymentPreference: String = "",
    val ModifiedAt: String = "",
    val ConnectedAccountId: String = "",
    val CreatedAt: String = "",
    val TipBalance: String = "",
    val EmployeeRemoteId: String = "",
    val PayoutUrl: String = "",
    val Notes: String = "",
    val LocationId: String = "",
)